language: python
sudo: required
python:
- 3.6.1
services:
- docker
env:
- CORE_PROJECT=template

install:
- ./dev-requirements.py  # install requirements in listed order
- scripts/clone.sh  # clone the core
script:
- cd core

- export PROJECT=template
- rapydo --project ${PROJECT} init && rapydo --project ${PROJECT} start
- rapydo --project ${PROJECT} shell backend --command 'restapi tests --wait'
# - rapydo --project ${PROJECT} shell backend --command 'mv .coverage .coverage.${PROJECT}'

- docker cp ${PROJECT}_backend_1:/code/.coverage .coverage.${PROJECT}
# - rapydo --project ${PROJECT} shell backend --command 'coverage combine'
- cd ..

after_success:
# NOTE: this works only with the base http api, and not in a real core fork
# FIXME: do as eudat for a configuration in core and use "rapydo coverage"
# - docker cp template_backend_1:/code/.coverage .
- coverage combine
- docker run -it -v $(pwd):/repo -w /repo $CORE_PROJECT/backend:template coveralls

deploy:
  provider: pypi
  user: pdonorio
  password:
    secure: YNjvWPNpfab00FD7EUwzDgXyorPFkefCk3C7PFDfB9yDaZFz6d/+Mk+HzJce84pqk0Nr0T8rrKVe7c69Ib+PgiYWrtYstnvKthZbN+IpFieEm/f72adG8rdSjLVb5gLNd49cqxfDIBD64V/DgkrJ5+Xif8j0D7d8CohKRqgFYdsAm0G9TiiAXqbaRGiUqEl6aJo1V2/8tDUNikWu3zCaHiCWYerHBf2IfeCdcsbX3qXwUje+g4ECRFH3kZbVD6YDS+47ib4GBuhJGGRMZDdICdk+MHXP1cRUv2EybmH5Q7cH8DZ+JoMuZNP/gQ3xT2Mt2wZ1n1le0wWfCNpkIdTPuOQTFrtxcZQycjDnVupu+mTDa4XCYgr3N0JFSJBVo9G+gYf9fswrt1BTtVBDpYUb0QGtZehFW+wuftNu10lvuibB1B3o1Vqf2TYO8CEgSfQy0c+VRt3oj0BuXnh+C5BxTFVYJpYoIlkDr4u0nomWosmMRyrSRP8i8CkJg4WEtlB//ZaU+9QkurQW3zPr8HetcRz5eIzX1rJPHLO4XIXGuCnc954OhXa6EaaouAHtGeYwYhYP1/wTtJKlBQUdADoYf37B4U8Mttxd6V9x/uRJXLhyt+hSKPPFsS0/PkRnum/B0Mfa70RPfibvgXxjLhq+vspWYty0J4wpxWJNbAQ7NVU=
  on:
    tags: true
